server:
    port: '${PORT:9093}'
eureka:
    client:
        serviceUrl:
            defaultZone: '${EUREKA_URL:http://localhost:9091}/eureka/'
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
ribbon:
    eureka:
        enabled: true
spring:
    cache:
        cache-names: 'tracksForGenre, temperatureFromCity, temperatureFromLocation'
        caffeine:
            spec: 'maximumSize=500, expireAfterAccess=600s'
spotify:
    api:
        url:
            token: 'https://accounts.spotify.com/api/token'
            recommendations: 'https://api.spotify.com/v1/recommendations'
        client:
            id: f8b486e527c2410c804e56b7f7dbc584
            secret: d887068aa5954cefb9dea84088908964
open-weather:
    api:
        url: 'http://api.openweathermap.org/data/2.5/weather'
        units: metric
        app-id: 867129315bff9e2983effe4f0fabf04c
